language: java

services:
  - docker
  
before_install:
  - chmod +x mvnw
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin >/dev/null 2>&1
  - docker build -t org.tmplcl/stuffboot .
  - docker tag org.tmplcl/stuffboot tmplcl/stuffboot
  - docker push tmplcl/stuffboot
  